### ISSUE TITLE
FQDN using host value

### ISSUE THREAD

**Issue by Cloud-Kid** [lbr38/repomanager#128]
Hi, 
Using podman-compose and the repomanager container as such :
```
  # Repomanager - Gestion des repos linux
  repomanager:
    restart: always
    container_name: repomanager
    hostname: repomanager
    environment:
      - FQDN=repomanager.my.fqdn.fr
      - MAX_UPLOAD_SIZE=32M
    ports:
      - '8080:8080'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './repomanager/repomanager-data:/var/lib/repomanager'
      - './shared/repomanager-repo:/home/repo'
    image: 'lbr38/repomanager:latest'
```
My FQDN in container is set to my docker host hostname in the GUI :
![Capture d’écran 2023-11-08 113614](https://github.com/lbr38/repomanager/assets/49484832/5e3f665f-890c-484e-bb3b-ba88300b64df)

So my clients can't reach the repository URL, but maybe it's only a podman issue.

Edit #1 :
If I check the FQDN ENV in container it's correct so it may be a bug :
![Capture d’écran 2023-11-08 113614](https://github.com/lbr38/repomanager/assets/49484832/60fbb0b8-8c96-4656-9953-3014de95de3d)
